on:
  push:
    branches : [main]
name: Deploy on push
jobs:
  web-deploy:
    name: Auto - Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: Burnett01/rsync-deployments@6.0.0
      with:
        switches: -avzr --exclude=".git"
        path: /
        remote_path: /home/u496810940/domains/bandungarabiccenter.com/bac/public/test
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: 65002
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        
