on:
  push:
    branches : [main]
name: Deploy on push
jobs:
  web-deploy:
    name: Auto - Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER}}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        port: 64000
        script: |
          cd test
          git pull 
        
